### ISSUE TITLE
Hide colour schemes when there's only one

### ISSUE THREAD

**Issue by johnbillion** [stuttter/wp-user-profiles#14]
When only one colour scheme is available, the `Color Scheme` panel should be hidden.

<img width="1189" alt="" src="https://user-images.githubusercontent.com/208434/27492567-90dd998c-583e-11e7-82fe-df75fa0be522.png">

Marking this as a bug because this behaviour differs from core.

**Comment by JJJ** [comment]
@johnbillion thanks for the issue here.

I'll poke the dragon, and say that I've always felt it odd that core jumps through the hoops it does to hide these on sites running from `src`.

Specifically, it's a barrier to creating new color schemes if they're only ever visible from `build`. I ran into this with the bbPress schemes, which may be why I made the decision to show a single one here.

Thoughts on keeping it the same? It might require some trickery to get in-between the metabox registration and display processes to unregister the box just-in-time.

**Comment by RichardCoffee** [comment]
I would vote for leaving it.  It let's people know there is only one color scheme available, and they can then make a choice as to whether they want more options in that regard.

**Comment by johnbillion** [comment]
I marked this as a bug only really as its behaviour differs from core. I'm not too bothered whether it stays or not, but it does look a bit odd.

**Comment by JJJ** [comment]
👍 hey @johnbillion good to see you! 💙
