### ISSUE TITLE
show_user_profile and edit_user_profile hooks not fired

### ISSUE THREAD

**Issue by johnbillion** [stuttter/wp-user-profiles#8]
I was looking into why some plugins don't appear to work with WP User Profiles active. It seems that the root cause is because the `show_user_profile` and `edit_user_profile` hooks aren't implemented. See https://core.trac.wordpress.org/browser/trunk/src/wp-admin/user-edit.php?rev=39907&marks=628-647#L626

I'm not sure which tab is most appropriate on which to fire this hook. Maybe the `Account` tab?

**Comment by JJJ** [comment]
Hey @johnbillion, thanks for noticing this. I omitted this intentionally, to not accidentally marry the plugin into a decision that was only mine to make at the time.

I did implement `personal_options_update` and `edit_user_profile_update` in the "correct" location (inside of the `wp_user_profiles_save_user()` function, in this plugin.)

I think in my imagination, it would be neat to use some `has_action( 'show_user_profile' )` magic to create an "Other" section on the fly, and output the HTML in a controlled manner there. Does that make sense? I think it's plausible, but I never got around to implementing it. It seems like the most friendly thing to do (to me, maybe for WordPress core too) but I could be convinced otherwise.

**Comment by JJJ** [comment]
Here's a screenshot of what some compatibility looks like. I hacked my WP User Avatars plugin quick to rely on the core actions vs. having baked-in WP User Profiles support:

<img width="1102" alt="screen shot 2017-03-25 at 3 47 42 pm" src="https://cloud.githubusercontent.com/assets/88951/24325620/e27b37ee-1172-11e7-88ed-532a3b384e5c.png">

The above pull-request will result in the above interface.

**Comment by lkraav** [comment]
Aha, so for confirmation - this is the reason why WooCommerce and its friends currently aren't showing its sections?

Perhaps this PR could be soft-launched by hiding behind a `apply_filters()` call for enabling.

Or is there something big I'm missing that's blocking the PR?

**Comment by JJJ** [comment]
@lkraav That is correct.

The only thing blocking it is a sanity check from anyone that it's working (at least) acceptably well.

**Comment by JJJ** [comment]
For WooCommerce specifically, it doesn't work because WC conditionally loads its user profile fields class only on the core page. I needed to core hack it to make it work, but it should be achievable with a small plugin to shim them together.

<img width="1440" alt="screen shot 2017-05-11 at 1 42 08 am" src="https://cloud.githubusercontent.com/assets/88951/25935955/24c0578c-35eb-11e7-9854-109dbf128b52.png">

**Comment by lkraav** [comment]
> The only thing blocking it is a sanity check from anyone that it's working (at least) acceptably well.

OK I'm taking on this sanity check work. Will clone the latest situation and report on findings.

Well, of stuff already known, step 1 would certainly be to just get WooCommerce core stuff working.

**Comment by JJJ** [comment]
Shipped in the 2.0.0 release. 💯
